# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: 初始化.NET编译环境
      uses: microsoft/setup-msbuild@v2
      with:
        dotnet-version: 9.0.x
    - name: 还原依赖项
      run: msbuild /t:Restore Rayer/Rayer.csproj
    - name: 构建
      run: msbuild /t:Build /p:RestorePackages=false Rayer/Rayer.csproj
    - name: 发布
      run: msbuild Rayer/Rayer.csproj /p:Configuration=Release /p:Platform="x64" /p:PublishProfile=FolderProfile /p:RuntimeIdentifier=win-x64 /p:PublishReadyToRun=true /t:Publish /p:AssemblyOriginatorKeyFile="$(Build.SourcesDirectory)\rayer.snk"
