# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:        
        working-directory: .

    steps:
    - uses: actions/checkout@v4.2.2
    - name: 初始化.NET编译环境
      uses: microsoft/setup-msbuild@v2
      with:
        dotnet-version: 9.0.x
    - name: 还原依赖项      
      run: msbuild /t:Restore
    - name: 构建      
      run: msbuild /t:Build /p:RestorePackages=false
    - name: 路径
      run: |          
          echo "工作目录: $GITHUB_WORKSPACE"
          echo "当前目录: $(pwd)"
          echo "当前目录内容: $(ls -la)"
    - name: 打印文件
      run: |          
          ls "$GITHUB_WORKSPACE/Rayer.Core/bin/x64/Release/net9.0-windows10.0.26100.0"
    - name: 发布
      run: msbuild /t:Restore /p:NoBuild=true /p:Configuration=Release /p:TargetFramework=net9.0-windows10.0.26100.0 /p:Platform="x64" /p:RuntimeIdentifier=win-x64 /p:PublishReadyToRun=true /t:Publish Rayer/Rayer.csproj
